version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api
    restart: unless-stopped
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend/logs.json:/app/logs.json
    environment:
      - NODE_ENV=production
      - PORT=4000
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
